### ISSUE TITLE
Apache Solr Support

### ISSUE THREAD

**Issue by riteshpuj2013** [RutledgePaulV/rest-query-engine#13]
My goal is to convert RSQL to Solr queries. I see that Elasticsearch is supported. As Elasticsearch and Solr both uses Lucene internally, so can we use the ElasticsearchVisitor for generating Solr query as well?
if not, can I use the code of ElasticsearchVisitor to create a SolrVisitor for Apache Solr as well?

P.S: I have not used Elasticsearch.

**Comment by RutledgePaulV** [comment]
You won't be able to use the elasticsearch visitor directly. However, like you said you could use the elasticsearch visitor as an example and write your own visitor that builds solr queries.

**Comment by RutledgePaulV** [comment]
I'm not planning on adding solr as part of the core visitors without a community offered PR to q-builders so I'm going to close this out.

**Comment by ypriverol** [comment]
Any progress on this. I'm interested to use it in solr
