### ISSUE TITLE
How to use rest-query-engine!!

### ISSUE THREAD

**Issue by ravi-chaurasia** [RutledgePaulV/rest-query-engine#2]
I have a project backed by mongodb. I Have written my own query based on each use cases.

I wanted to use rest-query-engine. But I can not find how to include this in my project. 

Please share some example about how can i include this in my project. 
If there is some maven repository please share.

**Comment by RutledgePaulV** [comment]
Hi Ravi,

I've updated the readme to contain this information. This codebase is pretty new and I haven't had a chance to get the test coverage to where I'd like (but I do think it largely works already!) before releasing to maven central. For that reason, at this time I can only offer you a snapshot version. I expect to bolster my coverage and release a 1.0 within the next week.

You can get the current snapshot (just pushed it) with the following bits added to your pom.xml

```xml
<dependencies>
    <dependency>
        <groupId>com.github.rutledgepaulv</groupId>
        <artifactId>rest-query-engine</artifactId>
        <version>0.5-SNAPSHOT</version>
    </dependency>
</dependencies>


<repositories>
    <repository>
        <id>ossrh</id>
        <name>Repository for snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by RutledgePaulV** [comment]
@ravi-chaurasia I'm going to close this out since I haven't heard anything from you. If you need any further assistance just let me know!

**Comment by ravi-chaurasia** [comment]
Hi @RutledgePaulV  

Thank you for the reply.

Sorry i was busy and I did not get a chance to look at your reply. 

That you for fast reply. 

yes this will work. 

Thanks.
