### ISSUE TITLE
Wildcard search

### ISSUE THREAD

**Issue by michaelassraf** [RutledgePaulV/rest-query-engine#23]
Hi,

We're trying to implement a wildcard search for Elasticsearch like this - 

`organizationId==18;(endpointHash=in=(f45879e539b140ebefc8cbcb3bac9d33);endpointPublisherProductVersions.publisherProductVersionsVersions.publisherProductVersionsPatchHash==0114ad06d728f1834e36fe1a39574ef4_0114ad06d728f1834e36fe1a39574ef4_*_PatchAvailable)`
But the string 0114ad06d728f1834e36fe1a39574ef4_0114ad06d728f1834e36fe1a39574ef4_*_PatchAvailable is treated as a plain string and not a wildcard query.

Any ideas?

Best,
Michael

**Comment by michaelassraf** [comment]
Hi - found =re= operator so closing this issue

**Comment by EufranioDiogo** [comment]
Super super helpful
