### ISSUE TITLE
Provide a non-snapshot version

### ISSUE THREAD

**Issue by wwadge** [RutledgePaulV/rest-query-engine#7]
Hi,

Can you do a non-snapshot release please? From what I can tell, this library is quite stable already.

**Comment by RutledgePaulV** [comment]
Hey! Sorry it took me so long to see this. I'm going to give this library some attention later today and make sure it's in a good state. Then I'm happy to cut a release!

**Comment by RutledgePaulV** [comment]
Okay, I did some cleanup and fixed known bugs and then did a release at version 0.7 that should be available in central shortly. Thanks for the poke!
