### ISSUE TITLE
Include MIT License headers and MIT license text

### ISSUE THREAD

**Issue by DanielMaier-BSI** [RutledgePaulV/rest-query-engine#9]
Hi,

first of all I really like this library. Never implemented a REST query API that fast. Thanks a lot.

Could you please add the MIT license header to the source files and include the MIT license into the archive. This would make us life easier :).

Many Thanks
Daniel

**Comment by RutledgePaulV** [comment]
Thanks Daniel! Yeah I can definitely do that today. I'll let you know when it's done.

**Comment by RutledgePaulV** [comment]
This should now be resolved with release 0.7.1

I also added regex support with that release!

**Comment by DanielMaier-BSI** [comment]
Thanks a lot.
